repositories:
- name: "repository-index"
  url: "https://get.mocaccino.org/mocaccino-repository-index"
  github: "https://github.com/mocaccinoOS/repository-index"
- name: "mocaccino-desktop-stable"
  url: "https://get.mocaccino.org/mocaccino-desktop-stable"
  github: "https://github.com/mocaccinoOS/desktop"
- name: "mocaccino-extra"
  type: "docker"
  url: "quay.io/mocaccino/extra"
  github: "https://github.com/mocaccinoOS/mocaccino-extra"
- name: "mocaccino-os-commons"
  type: "docker"
  url: "quay.io/mocaccino/os-commons"
  github: "https://github.com/mocaccinoOS/os-commons"
- name: "luet-official"
  url: "https://raw.githubusercontent.com/Luet-lab/luet-repo/gh-pages"
  github: "https://github.com/Luet-lab/luet-repo"
- name: "livecd"
  url: "https://raw.githubusercontent.com/Luet-lab/livecd-specs/gh-pages"
  github: "https://github.com/Luet-lab/livecd-specs"
- name: "kernel-stable"
  url: "https://get.mocaccino.org/mocaccino-kernel-stable"
  github: "https://github.com/mocaccinoOS/kernel-repo-stable"

BaseUrl: "https://packages.mocaccino.org"
