repositories:
- name: "repository-index"
  url: "https://get.mocaccino.org/mocaccino-repository-index"
  github: "https://github.com/mocaccinoOS/repository-index"
- name: "mocaccino-portage-tree"
  url: "https://get.mocaccino.org/mocaccino-portage-tree"
  github: "https://github.com/mocaccinoOS/portage-tree"
- name: "mocaccino-portage-tree-stable"
  url: "https://get.mocaccino.org/mocaccino-portage-tree-stable"
  github: "https://github.com/mocaccinoOS/portage-tree"
- name: "mocaccino-extra"
  url: "https://get.mocaccino.org/mocaccino-extra"
  github: "https://github.com/mocaccinoOS/mocaccino-extra"
- name: "mocaccino-extra-stable"
  url: "https://get.mocaccino.org/mocaccino-extra-stable"
  github: "https://github.com/mocaccinoOS/mocaccino-extra"
- name: "mocaccino-micro"
  url: "https://get.mocaccino.org/mocaccino-micro"
  github: "https://github.com/mocaccinoOS/mocaccino-micro"
- name: "mocaccino-micro-stable"
  url: "https://get.mocaccino.org/mocaccino-micro-stable"
  github: "https://github.com/mocaccinoOS/mocaccino-micro"
- name: "mocaccino-musl-universe"
  url: "https://get.mocaccino.org/mocaccino-musl-universe"
  github: "https://github.com/mocaccinoOS/mocaccino-musl-universe"
- name: "mocaccino-musl-universe-stable"
  url: "https://get.mocaccino.org/mocaccino-musl-universe-stable"
  github: "https://github.com/mocaccinoOS/mocaccino-musl-universe"
- name: "mocaccino-os-commons"
  url: "https://get.mocaccino.org/mocaccino-os-commons"
  github: "https://github.com/mocaccinoOS/os-commons"
- name: "mocaccino-os-commons-stable"
  url: "https://get.mocaccino.org/mocaccino-os-commons-stable"
  github: "https://github.com/mocaccinoOS/os-commons"
- name: "luet-official"
  url: "https://raw.githubusercontent.com/Luet-lab/luet-repo/gh-pages"
  github: "https://github.com/Luet-lab/luet-repo"
- name: "livecd"
  url: "https://raw.githubusercontent.com/Luet-lab/livecd-specs/gh-pages"
  github: "https://github.com/Luet-lab/livecd-specs"
- name: "kernel"
  url: "https://get.mocaccino.org/mocaccino-kernel"
  github: "https://github.com/mocaccinoOS/kernel-repo"
- name: "kernel-stable"
  url: "https://get.mocaccino.org/mocaccino-kernel"
  github: "https://github.com/mocaccinoOS/kernel-repo-stable"

BaseUrl: "https://packages.mocaccino.org"